---
title: "Data Wrangling"
author: "Jacky Wang"
format: html
editor: source
---

## Package

```{r}

# tidyverse
library(tibble)
library(dplyr)
library(stringr)

```

## Data Import

```{r}
load(file = "data/vegetable_ori.rda")
```


## Data Wrangling

### others

```{r}

tbl_others <- tbl_ori %>% 
    select(簽審核准許可文件編號, 報單項次, 受理日期)

```

```{r}

# 檢視缺失值 
tbl_others %>% 
    summarise(
        .data = ., 
        across(    # 套用至多個欄位
            .cols = everything(),    # tidy-select
            .fns = list(n_na = ~ sum(is.na(.x))),    # purrr-style lambda
            .names = "{.fn}({.col})"
        )
  )

# 檢視有無重複簽審
tbl_others %>% 
    summarise(., n_unique = n_distinct(簽審核准許可文件編號))

```

```{r}

# 檢視欄位內容格式

#   簽審編號
pat_sn <- "IF[A-Z]0[0-9][A-Z0-9]{2}[0-9]{7}"    # length 1 atomic vector
tbl_others %>% 
    summarise(., n_abnormal = sum(!str_detect(簽審核准許可文件編號, pat_sn)))

#   日期
pat_date <- "(201[1-9]|2020)-[0-9]{2}-[0-9]{2}"
tbl_others %>% 
    summarise(., n_abnormal = sum(!str_detect(受理日期, pat_date)))

rm(pat_sn, pat_date)
```

### main

#### target

```{r}

# tbl_ori$`批檢驗結果(除去標示因素)` %>% 
#     factor(., levels = c("合格", "不合格")) %>% 
#     summary()    # summary factor

# target
y <- tbl_ori$`批檢驗結果(除去標示因素)` %>% 
    factor(., 
        levels = c("合格", "不合格"),    # 將預測目標放後
        labels = c("Pass", "Fail")
    )

```

#### features

```{r}

# 黑名單因子
tbl_X_g1 <- tbl_ori %>% 
    select(contains("黑名單")) %>% 
    mutate(
        across(    # 套用至多個欄位
            .cols = everything(),    # tidy-select
            .fns = ~ factor(.x, levels = c("0", "1"), labels = c("no", "yes")), 
            .names = "{.col}_"    # 不改欄位名稱表示取代
        )
        , .keep = "none"    # 不保留原始資料
    ) %>% 
    rename(
         `黑名單產品(75%)` = `黑名單產品_`, 
         `黑名單號列(75%)` = `黑名單號列_`, 
         `黑名單號列(avg)` = `黑名單產品(舊)_`,
         `黑名單生產國(75%)` = `黑名單生產國_`,
         `黑名單進口商(75%)` = `黑名單進口商_`,
    )

# 檢視轉換結果
tbl_X_g1 %>% summary()

```

```{r}
# 嘗試迴圈寫法

```



```{r}

cols_exc <- c(names(tbl_others), "批檢驗結果(除去標示因素)")

tbl_ori %>% 
    select(!(all_of(cols_exc) | contains("黑名單")))

# 檢視每一欄位的值是否含 "無"

```



